### ISSUE TITLE
AppID invalid

### ISSUE THREAD

**Issue by MayhemBill** [Sniper677/ASF_ItemDropper#3]
I am trying to use this to farm TF2 items on an alt account, but when I run the command `istart <name> 440` it says the AppID is invalid, even though that is the correct ID for TF2

**Comment by MayhemBill** [comment]
actually testing now, it says all appids are invalid

**Comment by Sniper677** [comment]
Idling games with this plugin is not in focus anymore. It should be used only to trigger possible item drops.
As ASF has already this idle function implemented you better should use this to run your games.
The commands 'istart' and 'istop' are deprecated and not maintained anymore. They will be removed in the future.
